titre: "Neutre.Comobi"
mail: "comobi@beta.gouv.fr"
tel: "04 00 00 00 00"
nom: "Version Neutre"
formulaire: "https://docs.google.com/forms/d/e/1FAIpQLSfirgGZ4B_OnP3oe9q_CxMi3Lm5hpCyk_GSIdm9wtizvq3RMA/viewform?usp=sf_link"
formulaire_passager: "https://docs.google.com/forms/d/e/1FAIpQLScfZKk6qeVPw3zDVHnYl2Hzw6urgAXRYBXftW1WNb7CA325mA/viewform?usp=sf_link"
lien_cgu: "/cgu"
couleurs: 
  bouton_rechercher: "#199bb0"
  bouton_proposer: "#22aa75"
  odd_section_color: "#ecf0f1"
  header_btn_section: "#c9d622"

bandeau:
  image: "/images/banniere-neutre.png"
  texte: "Bandeau Neutre"

liste-logo:
  - images/ademe_logo.jpg
  - images/ANCT_Logo.jpg
  - images/beta_gouv_logo.jpg

## Les sections suivantes ne sont pas Ã  modifier
sass:
  sass_dir: _sass
  style: compressed

exclude:
  - direct/
  - outil-metier/
  - tests/

include:
  - _config.yml

code_source:
  instance: "https://github.com/betagouv/neutre.comobi.fr"
  comobi: "https://github.com/betagouv/comobi"

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true